FROM node:latest as build-stage
WORKDIR /app
COPY ./Client/package*.json ./
RUN npm install -g @quasar/cli && npm install
COPY ./Client/. .
RUN  chmod +x ./ -R
RUN quasar build -m pwa


FROM nginx:1.17.9

WORKDIR /app
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/dist/pwa /usr/share/nginx/html

EXPOSE 80 443
EXPOSE 40000-40200/udp
EXPOSE 40000-40200/tcp

CMD nginx -g "daemon off;"