version: "3.7"

services:
  web:
    image: dungeon2567/web-meetings:latest
    restart: always
    environment:
        MEDIASOUP_ANNOUNCED_IP: '45.55.58.119'
    ports:
      - "80:80"
      - "443:443"
      - "40000-40200:40000-40200/udp"
      - "40000-40200:40000-40200/tcp"