version: "3.7"

services:
  server:
    build:
      dockerfile: Dockerfile.server
      context: .
    restart: always
    ports:
      - "9008:9008"
      - "40000-40400:40000-40400/tcp"
      - "40000-40400:40000-40400/udp"
    environment:
        MEDIASOUP_ANNOUNCED_IP: '167.172.250.57'
  nginx:
    build:
      dockerfile: Dockerfile.client
      context: .
    restart: always
    depends_on: 
      - server
    ports:
      - "10080:80"
      - "10443:443"
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  networks:
    default:
      external:
        name: core-infra