version: "3.7"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
        MEDIASOUP_ANNOUNCED_IP: '45.55.58.119'
    ports:
      - "80:80"
      - "443:443"
      - "40000-40200:40000-40200/udp"
      - "40000-40200:40000-40200/tcp"
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot